apiVersion: "gerritoperator.google.com/v1alpha1"
kind: GitGarbageCollection
metadata:
  name: gitgc
spec:
  image: k8sgerrit/git-gc
  schedule: "*/5 * * * *"
  logPVC: logs-pvc
  site: gerrit
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 256Mi
