apiVersion: v1
kind: Namespace
metadata:
  name: gerrit-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gerrit-operator
  namespace: gerrit-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerrit-operator
  namespace: gerrit-operator
spec:
  selector:
    matchLabels:
      app: gerrit-operator
  template:
    metadata:
      labels:
        app: gerrit-operator
    spec:
      serviceAccountName: gerrit-operator
      containers:
      - name: operator
        image: tdraebingdev/gerrit-operator
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 1
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 30

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gerrit-operator-admin
subjects:
- kind: ServiceAccount
  name: gerrit-operator
  namespace: gerrit-operator
roleRef:
  kind: ClusterRole
  name: gerrit-operator
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gerrit-operator
rules:
- apiGroups:
  - "batch"
  resources:
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - '*'
- apiGroups:
  - "storage.k8s.io"
  resources:
  - storageclasses
  verbs:
  - 'get'
  - 'list'
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - "gerritoperator.google.com"
  resources:
  - '*'
  verbs:
  - '*'
