apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gerrit-master-ingress
  labels:
    app: gerrit-master
    chart: {{ template "gerrit-master.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.gerritMaster.ingress.maxBodySize | default "50m" }}
    {{ if .Values.gerritMaster.ingress.alias -}}
    nginx.ingress.kubernetes.io/server-alias: {{ .Values.gerritMaster.ingress.alias }}
    {{- end }}
spec:
  {{ if .Values.gerritMaster.ingress.tls.enabled -}}
  tls:
  - hosts:
    - {{ .Values.gerritMaster.ingress.host }}
    secretName: {{ .Release.Name }}-gerrit-master-tls-secret
  {{- end }}
  rules:
  - host: {{required "A host URL is required for the Gerrit master Ingress. Please set 'gerritMaster.ingress.host'" .Values.gerritMaster.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-gerrit-master-service
          servicePort: {{ .Values.gerritMaster.service.http.port }}
